name: CI/CD deploy main
on: 
  #push:
   # branches: [ "deploy-release"]
  pull_request:
    branches: [ "main"]
jobs:
 ci_cd_deploy_release:
    runs-on: ubuntu-latest
    permissions: 
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
       contents: write
    steps:
      - uses: actions/checkout@v2
      - run: echo 'hello world'
      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x

      - name: install dependencies 
        run: npm ci

      - name: build setup
        run: npm run build

      - name: list dir
        run: ls -la dist/mycv/browser
        
      - name: copy index.html, css, js
        run: cp dist/mycv/browser/*.* docs
        
      - name: list docs\
        run: ls -la docs
